public class Blinds {
    public static String CALL_OF_DUTY = "Call of Duty s return to World War II is surprisingly a fast paced take on the classic setting  It provides for a good campaign  a great new mode in multiplayer among other good changes  and a creepier  dense version of Nazi Zombies  However  each core part of Call of Duty  WW2 is marred by inconsistencies and minor flaws that hold it back from being a landmark in the series  Still  it s a solid Call of Duty game and I ve enjoyed the many hours I ve already poured into it  While my personal custom is to skip a Call of Duty campaign and jump straight into the multiplayer  this year I was happy to start Call of Duty  WW2 with this very personal feeling but typical war story  The campaign  which follows Private  Red” Daniels through pivotal moments like D Day (of course  and the liberation of Paris  is a good primer for what s to come  It shows how well Call of Duty s combat adjusts back into a historical setting for the first time since 2008 s World at War  and  more importantly  tells a good story with some fun action movie style spectacle  Over the short (or average  for this series  five  to six hour campaign  I slowly but surely found empathy for Daniels and his squad  The story is built mostly through excellently animated cutscenes and in narration after missions – the standard Call of Duty fare  I appreciate that while Daniels and his squad fought the obvious Nazi enemy  the tension between characters also developed as they found themselves deeper and deeper in the war  and that drove much of the drama  The squad isn t trying to take down the biggest  baddest enemy they can find  they re just trying to survive and do their best to make a difference as things get progressively worse  It s a more human perspective than we ve seen in recent years   The 1944 European setting definitely provides for an interesting Call of Duty experience  Taking a step away from a long stint of futuristic shooters – including last year s far future Infinite Warfare – this Call of Duty understandably loses a lot of the past games  verticality and speed  but that s not to say that combat is slow  It does require a bit more patience in identifying targets  more accurate shooting without the assistance of a variety of high tech scopes and sights  and it tacks on a campaign exclusive health bar for Daniels that requires constant attention  but enemies still drop fast and I still needed to keep constantly moving to stay alive  That s not to say the basic gunplay isn t solid  as it typically is with Call of Duty  but the Daniels  part in the war is a little more limited in terms of objectives and moment to moment gameplay  Though their appearances were fleeting  I appreciated the few diverse characters that highlighted the work of soldiers and resistance groups other than white American men in WW2" +
            "Call of Duty's long-awaited return to its World War II roots is not only a homecoming, but also a commemoration of the powerful bonds that form between brothers in arms. Yes, connecting with strangers through online matches and the Zombies mode isn't unusual, but Call of Duty: WWII's moving campaign also salutes the brotherhood that grows and strengthens on the battlefield. Moreover, this theme is cleverly tied to a gameplay mechanic where you rely on your company for resources. Seen through the eyes of an American soldier and a few other Allies, this affecting story offers brief glimpses of how the Nazi occupation ravaged Europe and its people, including German civilians. It's emblematic of a game that--along with its multiplayer modes--delivers practically everything that one looks for in a pick-up-and-play shooter set in the Western Front of World War II while also breaking free of Call of Duty's formulaic trappings.\n" +
            "\n" +
            "A first-person shooter set during the journey from Normandy to The Rhine isn't unique, but you haven't quite experienced anything like the tour of Ronald Daniels and the 1st Infantry Division in Call of Duty: WWII. It's a substantial, six-plus-hour trek where intense close-quarters combat complements spectacular showcase events, brought to life through excellent visuals and sound design. The booming cacophony of gunfire is fittingly accompanied by the crispness of the weapon reloads. And it's a journey rich in scenic environments that poignantly contrast against the death and destruction that surrounds you.\n" +
            "\n" +
            "A supporting cast of well-crafted personalities greatly enhances the narrative. Moreover, they directly assist you during combat based on your needs and performance. As your best friend, Robert Zussman fittingly takes care of your health pack supplies while the equally helpful Drew Stiles ensures you have enough grenades at the ready. And while the war-hardened William Pierson is an dispassionate commanding officer effectively played by Josh Duhamel, his eagle-eye skill with binoculars allows you to spot outlines of nearby enemies. These contributions are tied to a cooldown that decreases as you kill enemies. This kill-driven method of supply replenishment is undeniably gamified, but it's nonetheless a crafty way to serve the narrative's focus on bonding with your squad.\n" +
            "\n" +
            "While this is clearly Daniels' story, developer Sledgehammer thoughtfully shifts your perspective from time to time by putting you in other soldiers' boots, from Perez, a tank commander, to Rousseau, a French resistance operative. These valuable interludes relieve you of playing as the typical one-man army from start to finish. Sure, in the right hands, Daniels can be the war's greatest sniper and an accomplished AA gun operator in the same playthrough, but this campaign is a group effort and ultimately benefits from it.\n" +
            "\n" +
            "Combat itself is not about rushing forward to the next objective. It's about hunkering down at nearly every fallen table, picking off just enough Nazis to give you an opening to the next cover point. Whether you're toughing out every yard of forward progress with your best available machine gun, or quietly knifing Nazis in the tough-but-fair stealth sections, the campaign delivers a wealth of harrowing battles where checkpoints feel well-earned. And as you count on your squad for supplies and recon support, you feel empowered as a valuable team player in a company that has your back. The result is a level of gratification missing from the newsreel kitsch and globetrotting designs of the series' last foray into World War II, Call of Duty: World at War.\n" +
            "\n" +
            "It's a story supported with just the right amount of emotion, playing out both during firefights and periods in between. You have the option to add to your heroic reputation by saving wounded and exposed comrades or sparing surrendering Nazis. And Sledgehammer carefully humanizes Germans with dialogue that acknowledges the country's cultural contributions as well as having you play through a section where you help innocent civilians escape a heated warzone. Such small touches go a long way in adding heartfelt gravitas in a game focused on killing.\n" +
            "\n" +
            "Naturally foregoing the future tech and superhuman mobility of the last few CoDs, the return to mid-20th century combat is especially welcome in WWII's adversarial multiplayer. Fought across 10 diverse maps set throughout Europe, these locales accommodate all the series' basic weapon types, although the prevalence of tight and enclosed areas makes shotguns and submachine guns the popular weapons of choice in Team Deathmatch and other classic modes like the territorially driven Domination or Hardpoint. Whatever your preferred game type, the maps offer a solid mix of symmetrical floorplans like Flak Tower or labyrinthine layouts like the Ardenne Forest.\n" +
            "\n" +
            "\n" +
            "Gridiron--WWII's version of Uplink--proves that Capture The Flag converted into a ball carrying competition continues to have a place in COD multiplayer. Even without the advantages of double jumps and wall running, there's much strategy at play as you weave in and out of the ruins of Aachen, Germany or the docks of London, the latter toying with the fantasy of Nazis troops on UK soil. It's more nuanced than simply running the ball to the enemy's goal; success lies in knowing when to pass to a teammate or throw the ball forward, allowing you to sprint until you repossess the ball. It's also not unusual to find joy playing whole sessions in a supporting role, whether you're making yourself a diversionary target as the ball carrier's escort or drawing the ire of opponents by camping at your goal.\n" +
            "\n" +
            "If you are a sniper fan, your talents shine the brightest in War, Call of Duty: WWII's version of Battlefield's Rush. As a mode where one side of attackers attempt to conquer multiple segments of a map one section at a time, its multi-phase, linear format makes it a prime battleground for long-ranged weapons, whether you're picking off on-foot tank escorts or you're bold enough to zero in on bunker-based machine gunners. The asymmetrical format of assaulting and defending fits the D-Day invasion perfectly as one of the three available operations. Rather than limit the attacking side with finite respawns, the pressure is time-based. While this places the burden of success more on the aggressor's side, playing on either team presents distinct challenges and opportunities to be a valuable contributor. All operations proved involving and satisfying, no matter the side, which makes the limited selection of three sorties the one drawback of this otherwise stellar mode.\n" +
            "\n" +
            "Whatever your preferred armaments, Call of Duty: WWII's new Divisions class system excels by letting you make the most of your specific play style while offering the flexibility to diversify your loadouts. By joining the Expeditionary Force for example, you have the exclusive benefit of incendiary shotgun rounds, but that doesn't mean you can't switch to an assault rifle mid-match. The more you play, the more rewards you earn that can be spent to hone your personal armory and abilities to suit your needs. Adding to your identity-building are the myriad cosmetic items you unlock by opening supply crates, which are awarded regularly as you play. This blind box system plays out innocuously, with no pay-to-win shortcuts in sight, at least in the game's launch iteration.\n" +
            "\n" +
            "Tying these adversarial multiplayer modes together is the activity-rich social hub aptly titled Headquarters. Set against the backdrop of the Allied-occupied beaches of Normandy, this lively gathering spot is an inviting site to chill and train in ways impossible in standard issue multiplayer menus. Between the cluttered user interface and the checklist of available objectives, Headquarters feels overwhelming at first, but it speaks to the richness of this area's practical and entertaining activities. Along with completing goals related to the social aspects of Headquarters (e.g. commending your fellow soldiers) for modest amounts of in-game currency, greater rewards are in store if you activate Contracts. These timed challenges provide incentives to perform well in online matches beyond just maintaining a respectable kill/death ratio.\n" +
            "\n" +
            "Headquarters itself offers its share of stimulating gunplay. A real-time score duel against a stranger at the shooting range delivers a 30-second competitive thrill, but the marquee match is in the 1-vs-1 pit. Its single-weapon stakes are socially enhanced by letting those in the queue watch current matches while they wait their turn. This spectator appeal even extends to watching others open their loot crates, effectively echoing the childhood pastime of opening collectable card packs with friends. It's the place to feel motivated by higher ranking players who wear their prestige status icons proudly. Sledgehammer knows what a big deal prestiging is as evidenced by the fanfare and spectacle of a plane flybys when you reset your rank.\n" +
            "\n" +
            "Pairing cooperative play with the appeal of a goal-driven narrative, Zombies once again proves its worth as an essential Call of Duty mode. Titled The Final Reich, this survival mode of fantastical fiction pits players against waves of the undead in a Bavarian village. It's a setting as expansive outward as it is downward, where it can be easy to get separated in the midst of having to fend off zombies from all sides. When you're not busy trying to stay alive, you're completing objectives, activating switches, and uncovering the town's occult secrets, some involving symbols hidden in paintings scattered around the map. Those who thrive on multitasking will find the abundance of action items and the near relentless influx of brain-dead enemies positively engrossing. Yet you're delusional if you think you can complete The Final Reich after just a couple attempts.\n" +
            "\n" +
            "Like the best iterations of Zombies, this latest take is loaded with different forms of carrots that compel fans to come back again and again. Chief among these motivations is how it instills the belief that you and your friends can progress just a bit further in your next session. Along with naturally gaining a better familiarity of the map and the many zombie types, repeat playthroughs reward players with a host of meaningful upgrades and quality-of-life conveniences, from passive buffs to custom loadout slots. Sure, you can amass the highest body count among the team by playing with the Offense loadout, but imagine how much more valuable you'd be if you customized your ability set with a support skill normally reserved for Medics.\n" +
            "\n" +
            "Compared to multiplayer, loot crates in Zombies play a much larger, more practical role, adding to the mode's value as a compelling showpiece at the same level of Call of Duty: WWII's other game types. Any given pack can contain a game-changing consumable, whether that's a few free revives or a couple zombie-obliterating panzerschrecks. Figuring out when to use these valuable enhancements is part of the fun: Do you use your best consumables now to make a modicum of forward progress, or do you save these items for when you've committed the map layout and objectives to memory?\n" +
            "\n" +
            "Ultimately, if every shooter set in the European Theater of World War II is measured by how it depicts its D-Day landing--assuming it has such a mission--Call of Duty: WWII emphatically succeeds in its impactful designs and delivery. The sensation of riding the troop carrier as it approached the beach filled me with depression more than dread, knowing I'd survive eventually while many of my surrounding brothers in arms wouldn't. While not equally emotional, this battle's reinterpretation in War mode proves to be a highlight in a superb suite of competitive modes. Zombies rounds off this stellar return to form, effectively blending the ferocity of online cooperative play with the goal-driven satisfaction of found in the campaign. As one of the most comprehensive and filler-free Call of Dutys in recent memory, Call of Duty: WWII successfully capitalizes on the series' strengths.\n" +
            "\n" +
            "Reviewer's note: Call of Duty: WWII was primarily evaluated in a controlled \"review event\" environment hosted by Activision. As such, we haven't had the opportunity to fully test the online performance on public servers. Once we're able to do so, this review will be updated accordingly.\n" +
            "\n" +
            "Update: We've now spent a handful of hours in multiplayer matches with both the PS4 and Xbox One versions of the game. Though there were moments when lobbies were slow to load, and instances when Headquarters were empty, these issues were sporadic. Otherwise, matchmaking and connections have been largely stable. We've converted this into our final review, and have updated our score to reflect the Xbox One version of the game" +
            "npcs path source attacks area doesn period options number type release half reason studio nothing old somebody something";

    //Document visit = SiteVisit.visit("http://www.ign.com/articles/2017/11/08/call-of-duty-ww2-review");
    //String trimmedText = ContentTrimmer.trim("Call of Duty", visit);
        /*try (PrintWriter out = new PrintWriter("filename.txt")) {
            out.println(trimmedText);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }*/
}
