public class Blinds {
    public static String CALL_OF_DUTY = "Call of Duty s return to World War II is surprisingly a fast paced take on the classic setting  It provides for a good campaign  a great new mode in multiplayer among other good changes  and a creepier  dense version of Nazi Zombies  However  each core part of Call of Duty  WW2 is marred by inconsistencies and minor flaws that hold it back from being a landmark in the series  Still  it s a solid Call of Duty game and I ve enjoyed the many hours I ve already poured into it  While my personal custom is to skip a Call of Duty campaign and jump straight into the multiplayer  this year I was happy to start Call of Duty  WW2 with this very personal feeling but typical war story  The campaign  which follows Private  Red” Daniels through pivotal moments like D Day (of course  and the liberation of Paris  is a good primer for what s to come  It shows how well Call of Duty s combat adjusts back into a historical setting for the first time since 2008 s World at War  and  more importantly  tells a good story with some fun action movie style spectacle  Over the short (or average  for this series  five  to six hour campaign  I slowly but surely found empathy for Daniels and his squad  The story is built mostly through excellently animated cutscenes and in narration after missions – the standard Call of Duty fare  I appreciate that while Daniels and his squad fought the obvious Nazi enemy  the tension between characters also developed as they found themselves deeper and deeper in the war  and that drove much of the drama  The squad isn t trying to take down the biggest  baddest enemy they can find  they re just trying to survive and do their best to make a difference as things get progressively worse  It s a more human perspective than we ve seen in recent years   The 1944 European setting definitely provides for an interesting Call of Duty experience  Taking a step away from a long stint of futuristic shooters – including last year s far future Infinite Warfare – this Call of Duty understandably loses a lot of the past games  verticality and speed  but that s not to say that combat is slow  It does require a bit more patience in identifying targets  more accurate shooting without the assistance of a variety of high tech scopes and sights  and it tacks on a campaign exclusive health bar for Daniels that requires constant attention  but enemies still drop fast and I still needed to keep constantly moving to stay alive  That s not to say the basic gunplay isn t solid  as it typically is with Call of Duty  but the Daniels  part in the war is a little more limited in terms of objectives and moment to moment gameplay  Though their appearances were fleeting  I appreciated the few diverse characters that highlighted the work of soldiers and resistance groups other than white American men in WW2";

    //Document visit = SiteVisit.visit("http://www.ign.com/articles/2017/11/08/call-of-duty-ww2-review");
    //String trimmedText = ContentTrimmer.trim("Call of Duty", visit);
        /*try (PrintWriter out = new PrintWriter("filename.txt")) {
            out.println(trimmedText);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }*/
}
