/*
 * This file is generated by jOOQ.
 */
package sql;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import sql.tables.Keyword;
import sql.tables.ScrapedDocument;
import sql.tables.records.KeywordRecord;
import sql.tables.records.ScrapedDocumentRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>webcrawler</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<KeywordRecord, Integer> IDENTITY_KEYWORD = Identities0.IDENTITY_KEYWORD;
    public static final Identity<ScrapedDocumentRecord, Integer> IDENTITY_SCRAPED_DOCUMENT = Identities0.IDENTITY_SCRAPED_DOCUMENT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<KeywordRecord> KEY_KEYWORD_PRIMARY = UniqueKeys0.KEY_KEYWORD_PRIMARY;
    public static final UniqueKey<ScrapedDocumentRecord> KEY_SCRAPED_DOCUMENT_PRIMARY = UniqueKeys0.KEY_SCRAPED_DOCUMENT_PRIMARY;
    public static final UniqueKey<ScrapedDocumentRecord> KEY_SCRAPED_DOCUMENT_URL_UNIQUE = UniqueKeys0.KEY_SCRAPED_DOCUMENT_URL_UNIQUE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<KeywordRecord, Integer> IDENTITY_KEYWORD = Internal.createIdentity(Keyword.KEYWORD, Keyword.KEYWORD.ID);
        public static Identity<ScrapedDocumentRecord, Integer> IDENTITY_SCRAPED_DOCUMENT = Internal.createIdentity(ScrapedDocument.SCRAPED_DOCUMENT, ScrapedDocument.SCRAPED_DOCUMENT.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<KeywordRecord> KEY_KEYWORD_PRIMARY = Internal.createUniqueKey(Keyword.KEYWORD, "KEY_keyword_PRIMARY", Keyword.KEYWORD.ID);
        public static final UniqueKey<ScrapedDocumentRecord> KEY_SCRAPED_DOCUMENT_PRIMARY = Internal.createUniqueKey(ScrapedDocument.SCRAPED_DOCUMENT, "KEY_scraped_document_PRIMARY", ScrapedDocument.SCRAPED_DOCUMENT.ID);
        public static final UniqueKey<ScrapedDocumentRecord> KEY_SCRAPED_DOCUMENT_URL_UNIQUE = Internal.createUniqueKey(ScrapedDocument.SCRAPED_DOCUMENT, "KEY_scraped_document_url_UNIQUE", ScrapedDocument.SCRAPED_DOCUMENT.URL);
    }
}
