/*
 * This file is generated by jOOQ.
 */
package sql;


import javax.annotation.Generated;

import sql.tables.Keyword;
import sql.tables.ScrapedDocument;


/**
 * Convenience access to all tables in webcrawler
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>webcrawler.keyword</code>.
     */
    public static final Keyword KEYWORD = sql.tables.Keyword.KEYWORD;

    /**
     * The table <code>webcrawler.scraped_document</code>.
     */
    public static final ScrapedDocument SCRAPED_DOCUMENT = sql.tables.ScrapedDocument.SCRAPED_DOCUMENT;
}
