/*
 * This file is generated by jOOQ.
 */
package sql;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import sql.tables.Keyword;
import sql.tables.ScrapedDocument;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Webcrawler extends SchemaImpl {

    private static final long serialVersionUID = 1904568886;

    /**
     * The reference instance of <code>webcrawler</code>
     */
    public static final Webcrawler WEBCRAWLER = new Webcrawler();

    /**
     * The table <code>webcrawler.keyword</code>.
     */
    public final Keyword KEYWORD = sql.tables.Keyword.KEYWORD;

    /**
     * The table <code>webcrawler.scraped_document</code>.
     */
    public final ScrapedDocument SCRAPED_DOCUMENT = sql.tables.ScrapedDocument.SCRAPED_DOCUMENT;

    /**
     * No further instances allowed
     */
    private Webcrawler() {
        super("webcrawler", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Keyword.KEYWORD,
            ScrapedDocument.SCRAPED_DOCUMENT);
    }
}
